### ISSUE TITLE
SSL for Voyant. 

### ISSUE THREAD

**Issue by pguerr061703** [sgsinclair/Voyant#331] opened 2017-01-30 15:03 UTC
Hi,

Can you help me identify the tweaks for Voyant to be SSL ready?
When I run Voyant on a virtual server connected to a Netscalar( router), I get a spinning owl from the URL (cname). When I run voyant and point directly to the server name, it works fine.
Appears to be mixed content issue within Voyant (but I don't know how to fix it ).
I am running Voyant Server 2_2-M2 on a Redhat 6.8 virtual server
Any help would be greatly appreciated.

**Comment by sgsinclair** [comment] 2017-01-30 18:17
duplicate of https://github.com/sgsinclair/VoyantServer/issues/15

**Closed by sgsinclair** 2017-01-30 18:17 UTC

**Comment by pguerr061703** [comment] 2017-01-30 18:29
I am confused.  how do I resolve this issue ?

**Comment by sgsinclair** [comment] 2017-01-30 18:48
This issue isn't about Voyant, it's about VoyantServer which is why in my previous comment on pointed to the open ticket in that repository: https://github.com/sgsinclair/VoyantServer/issues/15
